WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
ERROR:django.request:Internal Server Error: /dogs/
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: dogs_base.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djangular/dogs/views.py", line 5, in home
    return render(request, 'dogs/home.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: dogs_base.html
ERROR:django.request:Internal Server Error: /dogs/
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: dogs_base.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djangular/dogs/views.py", line 5, in home
    return render(request, 'dogs/home.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: dogs_base.html
WARNING:django.request:Not Found: /dogs/home
ERROR:django.request:Internal Server Error: /dogs/
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: dogs_base.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djangular/dogs/views.py", line 5, in home
    return render(request, 'dogs/home.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: dogs_base.html
WARNING:django.request:Not Found: /superheroes/hero/Batman
WARNING:django.request:Not Found: /superheroes/herodetails/Batman
WARNING:django.request:Not Found: /superheroes/herodetails/Superman
INFO:root:Created superhero Superman
INFO:root:Created superhero Superman
INFO:root:Created superhero Wonder Woman
INFO:root:Created superhero Wonder Woman
INFO:root:Created superhero Spider-Man
INFO:root:Created superhero Spider-Man
INFO:root:Created superhero Iron Man
INFO:root:Created superhero Iron Man
WARNING:django.request:Not Found: /superheroes/herodetails/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/herodetails/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/herodetails/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/herodetails/{% static 'js/superheroes.js'
WARNING:django.request:Not Found: /superheroes/{% static 'js/superheroes.js'
ERROR:django.request:Internal Server Error: /dogs/
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: dogs_base.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djangular/dogs/views.py", line 5, in home
    return render(request, 'dogs/home.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: dogs_base.html
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Created superhero Superman
INFO:root:Created superhero Superman
INFO:root:Created superhero Wonder Woman
INFO:root:Created superhero Wonder Woman
INFO:root:Created superhero Spider-Man
INFO:root:Created superhero Spider-Man
INFO:root:Created superhero Iron Man
INFO:root:Created superhero Iron Man
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
