WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /export/
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 6, in home
    return render(request, 'export/home.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
ERROR:django.request:Internal Server Error: /export/
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 6, in home
    return render(request, 'export/home.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/defaulttags.py", line 1376, in url
    viewname = parser.compile_filter(bits[1])
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 700, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':export_csv' from 'export:export_csv'
ERROR:django.request:Internal Server Error: /export/
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 6, in home
    return render(request, 'export/home.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/defaulttags.py", line 1376, in url
    viewname = parser.compile_filter(bits[1])
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 700, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':export_csv' from 'export:export_csv'
ERROR:django.request:Internal Server Error: /export/
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 6, in home
    return render(request, 'export/home.html', context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_csv' not found. 'export_csv' is not a valid view function or pattern name.
ERROR:django.request:Internal Server Error: /export/export_csv
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 10, in export_csv
    return render(request, 'export/finished.html')
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/defaulttags.py", line 1376, in url
    viewname = parser.compile_filter(bits[1])
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 700, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''export:home;' from ''export:home;'
ERROR:django.request:Internal Server Error: /export/export_csv
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 10, in export_csv
    return render(request, 'export/finished.html')
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/defaulttags.py", line 1376, in url
    viewname = parser.compile_filter(bits[1])
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/base.py", line 700, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''export:home;' from ''export:home;'
ERROR:django.request:Internal Server Error: /export/export_csv
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 14, in export_csv
    writer = csv.writer(response)
NameError: name 'csv' is not defined
ERROR:django.request:Internal Server Error: /export/export_pdf
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 25, in export_pdf
    return render(request, 'export/finished.html')
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: export/finished.html
INFO:root:Created superhero Superman
INFO:root:Created superhero Superman
INFO:root:Created superhero Wonder Woman
INFO:root:Created superhero Wonder Woman
INFO:root:Created superhero Spider-Man
INFO:root:Created superhero Spider-Man
INFO:root:Created superhero Iron Man
INFO:root:Created superhero Iron Man
ERROR:django.request:Internal Server Error: /export/export_csv
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 20, in export_csv
    writer.close()
AttributeError: '_csv.writer' object has no attribute 'close'
ERROR:django.request:Internal Server Error: /export/export_csv
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 20, in export_csv
AttributeError: '_csv.writer' object has no attribute 'close'
ERROR:django.request:Internal Server Error: /export/export_pdf
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 31, in export_pdf
    pdf.draw_string(100, i, str(hero))
AttributeError: 'Canvas' object has no attribute 'draw_string'
ERROR:django.request:Internal Server Error: /export/export_pdf
Traceback (most recent call last):
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jstrick/Documents/curr/courses/python/examples3/django1.11/djexport/export/views.py", line 35, in export_pdf
    pdf.drawString(x_pos+200, y_pos, hero.city)
  File "/Users/jstrick/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/reportlab/pdfgen/canvas.py", line 1542, in drawString
    text = text.decode('utf-8')
AttributeError: 'City' object has no attribute 'decode'
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
